[project]
name = "bqat"
version = "1.8.6"
license = "Apache-2.0"
description = "Biometric Quality Assessment Tool - CLI (BQAT-CLI)"
readme = "README.md"
authors = [{ name = "Liam Wu", email = "liam.wu@biometix.com" }]
requires-python = ">=3.10,<3.15"
dependencies = []
keywords = [
  "bqat", "cli", "biometric"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Scientific/Engineering :: Image Processing",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
Documentation = "https://biometix.github.io/getting_started/cli.html"
Changelog = "https://biometix.github.io/changelog/#bqat-cli"
Repository = "https://github.com/Biometix/bqat-cli"
Releases = "https://github.com/Biometix/bqat-cli/releases"
Issues = "https://github.com/Biometix/bqat-cli/discussions"

[project.scripts]
bqat = "bqat:cli.main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pyinstaller>=6.18.0"]
